### ISSUE TITLE
OSD stays in regular position

### ISSUE THREAD

**Issue by l3ifk** [witalihirsch/Mono-gtk-theme#17]
The OSD is in its original position and not as shown in the previews in the top panel integrated. When trying to adjust position and transparency with the extension Better-OSD the position can be adjusted. However, enabling transparency does not fully make the OSD transparent. A white border is left which really disturbs the look.

Edit: I'm using Ubuntu 22.04.1 LTS with Gnome 42.5

**Comment by witalihirsch** [comment]
I had to drop the previous concept because it requires additional extensions, so now it looks like this
![image](https://user-images.githubusercontent.com/73841541/201975680-bf96e31b-fc02-4f6d-8682-2f66640c66e1.png)
![image](https://user-images.githubusercontent.com/73841541/201975705-d49d9542-77fc-412d-a480-e967bcc017db.png)
you can download 0.7 version of gnome-shell from releases if you want osd on top and with better osd move it to panel

**Comment by l3ifk** [comment]
okay I understand thank you!
