### ISSUE TITLE
Gnome dash to dock partially outside the screen

### ISSUE THREAD

**Issue by jakubpawlina** [witalihirsch/Mono-gtk-theme#25]
# Gnome dash to dock partially outside the screen

### Description

Setting `extend-height` in dash-to-dock to true causes in displaying it partially outside the screen.

### Screenshot
Red borders are the edges of the screen.

![Screenshot from 2022-12-11 11-40-32](https://user-images.githubusercontent.com/29257057/206899142-77d9d283-12e1-419f-b3e0-3c548f088e00.png)

### Environment
DE: Gnome 43.0

**Comment by witalihirsch** [comment]
What is your screen resolution? Maybe this is the reason, I noticed that your dock corners are more rounded. Maybe I misunderstood you, because the screenshots aren't very legible, but on my screen everything is displayed correctly. I'm attaching different options, because I didn't realize what you mean
![image](https://user-images.githubusercontent.com/73841541/206981622-85b78d00-1706-45de-a9f1-0c382cab5902.png)
![image](https://user-images.githubusercontent.com/73841541/206982020-be49ac1e-183f-42de-84fd-7e743c2cf040.png)
![image](https://user-images.githubusercontent.com/73841541/206982113-0e311d66-0d58-4b77-97a7-04e26f2fa9f4.png)
