### ISSUE TITLE
Disproportionately small padding near the ends of dash to dock

### ISSUE THREAD

**Issue by jakubpawlina** [witalihirsch/Mono-gtk-theme#26]
# Disproportionately small padding near the ends of dash to dock
### Description
When there are a lot of apps in the dash to dock (when scrolling is needed), the padding near the ends of it are very small. It might be a good idea to make them proportional everywere.

### Screenshots
![Screenshot from 2022-12-11 11-54-38](https://user-images.githubusercontent.com/29257057/206899625-a8f007f4-17d0-425b-a3e2-ec253b7681f8.png)

### Environment
DE: GNOME 43.0

**Comment by witalihirsch** [comment]
Is this problem only with my theme or with others too? And in fact, again, the problem isn't entirely clear from the screenshot, it's better to record a video as it's displayed while scrolling. I would record a video myself, but there are now some problems due to which the video isn't recorded. I've no problem with padding whichever side the dock is on, so it seems to me that it has something to do with screen resolution
![image](https://user-images.githubusercontent.com/73841541/206983752-6546ad9b-68c2-4482-aa1e-ae063363bc72.png)
![image](https://user-images.githubusercontent.com/73841541/206984706-5ebfbb88-ba5b-4264-ad6f-9630a43ae25e.png)
